export const dateFormats = [
  'dd-MM-yy',
  'dd-MM-yyyy',
  'MM-dd-yyyy',
  'yyyy-MM-dd',
  'yyyy-MM-dd HH:mm:ss',
  'yyyy-MM-dd HH:mm:ss.SSS',
  'yyyy-MM-dd’T\'HH:mm:ss',
  'yyyy-MM-dd’T\'HH:mm:ssZ',
  'yyyy-MM-dd’T\'HH:mm:ss.SSS',
  'yyyy-MM-dd’T\'HH:mm:ss.SSSZ',
  'yy-MM-dd HH:mm:ss',
  'MM/dd/yyyy HH:mm:ss',
  'MM/dd/yy h:mm aa',
  'MM/dd/yy HH:mm:ss',
  'MM/dd/yy HH:mm',
  'MM/dd/yy HH:mm a',
  'MMM dd, yyyy HH:mm a',
  'MMM dd yyyy HH:mm:ss',
  'dd/MM/yyyy HH:mm:ss a',
  'dd/MM/yy HH:mm:ss a',
  'MM/dd/yy',
  'MM/dd/yyyy',
  'Yyyy',
  'h:mm a',
  'HH:mm:ss',
];
